global using InterviewCase.Models.Models;
global using InterviewCase.Services.IServices;
global using Microsoft.AspNetCore.Mvc;
global using InterviewCase.Models.DBModel;
global using InterviewCase.Models.DTO;
global using Microsoft.EntityFrameworkCore;
global using InterviewCase.Models.Context;
global using InterviewCase.Services.Services;
global using AutoMapper;